### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by wertercatt** [RaineBannister/LUJS#2]
```
C:\Users\Blaze\Downloads\LUJS-master>node index.js
Rebuilding the database
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1156:14)
    at Function.setupDatabase (C:\Users\Blaze\Downloads\LUJS-master\Loader.js:64:16)
    at Function.setup (C:\Users\Blaze\Downloads\LUJS-master\Loader.js:12:14)
    at Object.<anonymous> (C:\Users\Blaze\Downloads\LUJS-master\index.js:15:8)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by uwainium** [comment]
this issue is due to Node changing the requirements of fs.writeFile to require a callback. To fix, either use node < 10, or change Loader.js line 64 to include a callback as the final parameter. I have a host of other stuff to push at some point, so it will be fixed then.

**Comment by uwainium** [comment]
Fixed in most recent commit
